name: Python package
on:
  workflow_dispatch:
    inputs:
      sol:
        description: "Selecciona que parte seleccionar"
        required: true
        type: choice
        options:
          - full
          - front
          - back
          - data
jobs:
  punto:
    runs-on: ubuntu-latest
    steps:
      - name: fullstack
        if : ${{inputs.sol == 'full' }}
        run: zip -r repo.zip7
      - name: front
        if : ${{inputs.sol == 'front' }}
        run: zip -r templates.zip templates/
      - name: back
        if : ${{inputs.sol == 'back' }}
        run: zip -r backend.zip app.py validation.py encriptation.py
      - name: data
        if : ${{inputs.sol == 'data' }}
        run: zip -r data.zip data/
